### PR TITLE
Add support for "mini-pill" hardware variant

### PR DESCRIPTION
**Pull request by serisman**
JS,

Hopefully this is close to what you had in mind to support hardware variants.

I also added a 'program-dfu' make target to make it slightly easier to program the STM32 via the USB DFU bootloader.

### CODE REVIEW

**Comment by freepdk** [comment]
Have you tested the ADC ?

Please use the "easypdkprogtest" target to create this extra pc executable and then run it... it should give you 3 ADC readings: VREF = 3.3V  VDD=5.0V VPP=5.0V (+/- some millivolts).

**Comment by serisman** [comment]
> Have you tested the ADC ?

I have now.  (And, I found a bug in the ADC channel numbers, which has since been fixed.)  Thanks for the tip.

> Please use the "easypdkprogtest" target to create this extra pc executable and then run it... it should give you 3 ADC readings: VREF = 3.3V VDD=5.0V VPP=5.0V (+/- some millivolts).

```
>easypdkprogtest
vdd: 5.00   vpp: 4.99    (vref= 3.30)
```

**Comment by serisman** [comment]
This is still working after changing to the development branch.

**Comment by freepdk** [comment]
I created a new feature branch for hardware variants.

I added 2 HW detect pins in CubeMX (CubeMX is the start point and auto generator for the base project). 
Then I added a manual reconfigure of ADC inside of fpdk.c source file (we do not have control over the places where you added your changes since they are auto-generated by CubeMX).

If you have the time, please checkout the hwvariants feature branch and test if easypdkprogtest reports correct ADC values for your hardware.

**Comment by serisman** [comment]
> I created a new feature branch for hardware variants.
> 
> I added 2 HW detect pins in CubeMX (CubeMX is the start point and auto generator for the base project).
> Then I added a manual reconfigure of ADC inside of fpdk.c source file (we do not have control over the places where you added your changes since they are auto-generated by CubeMX).
> 
> If you have the time, please checkout the hwvariants feature branch and test if easypdkprogtest reports correct ADC values for your hardware.

Thanks JS,

I did a quick skim of the feature/hwvariants branch.  The only thing that jumped out was this code in the FPDK_Init method:
```
  uint32_t hwdet = (HAL_GPIO_ReadPin(HW_VARIANT_DET0_GPIO_Port, HW_VARIANT_DET0_Pin)?0:1) |
                   (HAL_GPIO_ReadPin(HW_VARIANT_DET1_GPIO_Port, HW_VARIANT_DET1_Pin)?0:2);

  switch( hwdet )
  {
    case 1: _hw_variant = FPDK_HWVAR_MINI_PILL; break;

    default:
      _hw_variant = FPDK_HWVAR_NONE;
  }
```

I had to think about how hwdet was calculated for a bit, and it seems backwards at first (because of the pin pull-ups, with the hardware pulling to gnd).

I wonder if it would be better to reverse the logic so it would be `case 2:` or `case 0b00000010:` (i.e. 2nd hwid pin toggled)?

I will pull down this branch and test it against actual hardware later today.

**Comment by cpldcpu** [comment]
@serisman  just to double check:

- You mini Pill pull PB9 down and lets PB8 float?
- The lite version pulls PB8 down and lets PB9 float.

**Comment by serisman** [comment]
Yes, that is correct.

image

**Comment by cpldcpu** [comment]
ok, thanks. Was also a bit confused about the hwid implementation.

**Comment by serisman** [comment]
> ok, thanks. Was also a bit confused about the hwid implementation.

Yes, it really makes you think about it.

The `uint32_t hwdet = (HAL_GPIO_ReadPin(HW_VARIANT_DET0_GPIO_Port, HW_VARIANT_DET0_Pin)?0:1) |
                   (HAL_GPIO_ReadPin(HW_VARIANT_DET1_GPIO_Port, HW_VARIANT_DET1_Pin)?0:2);` is creating a mask that is the inverse of the pins.  So, PB9 -> GND, PB8 -> float = 0b00000010, which is '2' not '1'.

**Comment by cpldcpu** [comment]
Well,. it's not a huge problem. Would help to add a comment to the hwid, describding which pins are used

**Comment by serisman** [comment]
> Well,. it's not a huge problem. Would help to add a comment to the hwid, describding which pins are used

I assume you are working on a PR to add support for the "Lite" version?  Why not include a comment to describe that in your PR?  :wink:

**Comment by cpldcpu** [comment]
Of course I do!

**Pull request closed without merging**
