### PR TITLE
add define for wdreset command

### PR DESCRIPTION
**Pull request by electroniceel**

### CODE REVIEW

**Comment by electroniceel** [comment]
I based this on the development branch, not on master. The pull request added the other commits from the development branch too. Don't know what the correct way in github is to request a merge into a branch that is not master.

**Comment by freepdk** [comment]
good question.... indeed i have no idea how to pull request on dev branch as well.

I manually put this in dev branch.

**Comment by cpldcpu** [comment]
@freepdk I think you can use the the desktop software or the shell to commit branches to main. I used to do this in the past.

**Comment by electroniceel** [comment]
Thanks for merging. 

I'll try to find a better way to create pull requests in github when I do the next patch. Or do you prefer a different workflow?

**Pull request closed without merging**
