### PR TITLE
Simplify the calibration configuration

### PR DESCRIPTION
**Pull request by serisman**
I am creating this draft PR so we have a place to review and discuss the work that is already underway.

The purpose of this refactor is to make it easier to add support for additional ICs, and reduce the number of custom calibration algorithms by having fewer customizable algorithms.  Additional, the stability of calibration can be improved by starting at 0x00 instead of 0xFF.

### CODE REVIEW

**Comment by serisman** [comment]
@freepdk 

Loving the new calibration routines! 👍 

One thought... for better backwards compatibility, it might be wise to leave the old calibration algorithms in fpdkiccalib.c (at least the ones that were there for the 1.2 release).  That way if someone updates their programming software but is still using a previous version of the include files, or a previously generated hex file, calibration would still work.  I think it is safe to remove them from the include files, however, so that any newly compiled code will use the new algorithms.

**Comment by david-sawatzke** [comment]
> for better backwards compatibility, it might be wise to leave the old calibration algorithms

I concur. Keeping BC compatability to old binaries seems *very* important to me. Updating the programmer file breaking old binaries is unexpected behavior. Especially since the past releases have already been stable.

This would also allow to keep a common base of calibration algorithms over different programmers (the few that exist) more easily.

**Comment by freepdk** [comment]
I will see if this can be achieved.

If not I will put a warning for unknown/unsupported calibration algorithms in easypdkprog which tells the user to recompile the application or to use the older easypdkprog/firmware release.

On the other hand, what about using newer macros and try to flash them with old programmer software/firmware ...

So my best idea right now is to put a new logic in easypdkprog that in case an unknown magic block (>5 "AND A,<IMM>" instructions in a row) is found it will warn and abort flashing (with extra option ignore this to flash anymway).

With this logic problems will be deteced in future updates / changes.

**Comment by freepdk** [comment]
I think it is good to be merged into development.

Tested 13, 14 and 15 bit ICs.

Also, all old / unknown / new magic patterns are detected and programing is aborted.

**Comment by serisman** [comment]
Great news!  I'll pull it down and try it out later today.  But, don't wait for me.  If you are happy with it, feel free to merge it whenever.

**Comment by serisman** [comment]
I was able to pull down this branch and give it a test.

I specifically tested a PFS154 and PFS173, run both of them through all the available examples.

Looks good to me.

**Pull request merged**
