### PR TITLE
Add support for PMS171B

### PR DESCRIPTION
**Pull request by david-sawatzke**
Tasks:
- [x] Port headerfile
- [x] Add to makefile
- [x] Add to programmer
- [x] Add binaries
- [x] Test if it works at all
- [x] Update README
- [x] Fix calibration for ilrc & bg

### CODE REVIEW

**Comment by serisman** [comment]
@david-sawatzke - Having spent several hours yesterday doing the same thing for the PMS152 and learning how it all fits together, I can help you out with some of this.

For the FUSE stuff, the best resource I found is the original include files from the Padauk IDE.

Towards the top, you will find a section like this:
```
.Assembly	ASM_INSTR	SYM_85A
	.Assembly	OPTION	0	Security	Enable	Disable
	.Option_Help
	{
		Security	: 	"Security select"
		Enable		: 	"Security 7/8 words Enable"
		Disable		: 	"Security Disable"
	}
	.Assembly	OPTION	10	Bootup_Time	Slow	X	X	Fast
	.Assembly	OPTION	8	PB4_PB5_Drive	Normal	Strong
	.Assembly	OPTION_VIRTUAL	Comparator_Edge		All_Edge	Rising_Edge		Falling_Edge
	.Assembly	OPTION_VIRTUAL:8	LVR		X  4.0V  X  3.5V  X  X  3.0V  2.7V  2.5V  X  X  2.2V  X  2.0V  X  1.8V
	.Assembly	OPTION_LOW	1, 9, 13 ~ 15
	.Assembly	OPTION_DEFAULT	0x1DFC
	.Assembly	OTHER_HIGH
```

These are the important bits:
```
	.Assembly	OPTION	0	Security	Enable	Disable
	.Assembly	OPTION	10	Bootup_Time	Slow	X	X	Fast
	.Assembly	OPTION	8	PB4_PB5_Drive	Normal	Strong
	.Assembly	OPTION_LOW	1, 9, 13 ~ 15
	.Assembly	OPTION_DEFAULT	0x1DFC
	.Assembly	OTHER_HIGH
```
This is telling us that bit 0 is the Security bit, bit 10 is the Bootup Time bit, bit 8 is the PB4/PB5 IO Drive bit, and bits 1, 9, 13-15 should be LOW, and everything else HIGH.

This would translate into:
```
//fuse definitions
#define FUSE_SECURITY_ON   0x0000 //(S)
#define FUSE_SECURITY_OFF  0x0001
#define FUSE_PB4PB5_NORMAL 0x0000 //(D)
#define FUSE_PB4PB5_STRONG 0x0100
#define FUSE_BOOTUP_SLOW   0x0000 //(B)
#define FUSE_BOOTUP_FAST   0x1800
#define FUSE_RES_BITS_HIGH 0x10FC // - - 0 1   B B 0 D   1 1 1 1   1 1 0 S

```

If you are looking at the 'Code Options' in the datasheet, you will notice a bunch of other stuff listed.  The rest of those can be found by looking at the MISC2, MISC_LVR, and ROP registers:

```
	MISC2		IO_WO:OP	0x0F (-)
		$ 6 ~ 5	:	Both, Rising, Falling	//	ref :	ICE_INSTR.OPTION_HIGH

	MISC_LVR		IO_WO:OP	0x35
		$ 7 ~ 4 :	1V8, 1V9, 2V, 2V1, 2V2, 2V3, 2V4, 2V5, 2V7, 3V, 3V15, 3V3, 3V5, 3V75, 4V, 4V5
		$ 1 ~ 0	:	BG_On, BG/4, BG/32, BG_Auto

	ROP		IO_WO:OP	0x3A (0x2A)
		$ 7	:	TMx_16MHz, TMx_32MHz
		$ 6	:	PURE_PWM, GPC_PWM
		$ 5	:	TMx_6BIT, TMx_7BIT
		$ 4 :	TM2_PB2, TM2_PB0
		$ 3 ~ 2	=	X
		$ 1	:	PA0, PB5
		$ 0	:	PB0, PA4
```

You can probably find similar settings in the other .h files for each of these.

At a glance, the values for pfs173 look the same for MISC2 and MISC_LVR:
```
//misc2 definitions
#define MISC2_COMP_EDGE_INT_BOTH     0x00
#define MISC2_COMP_EDGE_INT_RISE     0x20
#define MISC2_COMP_EDGE_INT_FALL     0x40

//misc_lvr definitions
#define MISCLVR_1V8                  0x00
#define MISCLVR_1V9                  0x10
#define MISCLVR_2V                   0x20
#define MISCLVR_2V1                  0x30
#define MISCLVR_2V2                  0x40
#define MISCLVR_2V3                  0x50
#define MISCLVR_2V4                  0x60
#define MISCLVR_2V5                  0x70
#define MISCLVR_2V7                  0x80
#define MISCLVR_3V                   0x90
#define MISCLVR_3V15                 0xA0
#define MISCLVR_3V3                  0xB0
#define MISCLVR_3V5                  0xC0
#define MISCLVR_3V75                 0xD0
#define MISCLVR_4V                   0xE0
#define MISCLVR_4V5                  0xF0
#define MISCLVR_BANDGAP_ON           0x00
#define MISCLVR_BANDGAP_DIV4         0x01
#define MISCLVR_BANDGAP_DIV32        0x02
#define MISCLVR_BANDGAP_AUTO         0x03
```

The ROP looks similar but slightly different, but should be easy enough to figure out.

Hope this helps.

**Comment by serisman** [comment]
For the CALIBRATE macros, do the following:

First, you need to figure out if this IC needs the PADIER fix.  The datasheet is wrong on some of these ICs when it mentions that the reset value is 0xFF.  I spent hours yesterday and today fighting with the PMS152 before figuring out that PADIER.4 needs to be set to 1 or else the calibration routines won't work properly.  I'm not sure if that will apply to this IC or not.

Then, you need to take a look at the available algorithms in the fpdkiccalib.c file.  You are looking for a block that matches the type (i.e. IHRC, ILRC, or BG), architecture (i.e. codebits=14 for pdk14 ICs), and where the register addresses for PAC, PA, IHRCR, and possibly PADIER match.  For instance, the 14-bit H8 algo uses 0x11 for PAC, 0x10 for PA, and 0x0B for IHRCR but does not set PADIER (for that you would need H10).  If you can't find one that matches, a new algo would need to be added in this file and also the pdkcommon.h file.

**Comment by serisman** [comment]
For programmer support, you might luck out (like I did with the PMS152) and it just works.

The PMS171B already has probe support, so at least some of the harder stuff is already implemented.

You will need to modify fpdkicdata.c to un-comment the appropriate lines, and then recompile easypdkprog in order to test things.

If this doesn't just work, you will probably need help from JS or someone else who can analyze the real programmer's data streams.

**Comment by serisman** [comment]
You might also want to review my PR (https://github.com/free-pdk/easy-pdk-programmer-software/pull/25) where I already went through all of this for the PMS152.  (I still need to fix the ILRC and BG calibration)

I also made some bug fixes and consistency tweaks and renames to the existing device .h include files, which would be good to keep consistent.

**Comment by serisman** [comment]
One other comment:

This is a OTP part, which usually don't have factory IHRC calibration, so you will probably want to remove the EASY_PDK_USE_FACTORY_IHRCR_16MHZ definition.

And for the EASY_PDK_USE_FACTORY_BGTR it looks like you based the address off of a flash based part, but you really need to verify this by first reading a blank IC, loading it up in a hex viewer and finding the exact address that has the calibration value.

For instance (for the PMS152):
image

The word at address 0x09EC clearly has something in it.  Divide the address by 2 (because this needs to be word based) to arrive at a location of 0x4F6.  The flash based ICs seem to have three factory calibration values (IHRC, BG, and ILRC) where the OTP ICs seem to only have the IHRC factory calibration value.

You can also notice the default FUSE value (0x1FFD in this case) at the very last location (0x9FE -> 0x4FF in this case).

**Comment by kaweksl** [comment]
FPPA IDE also sets PADIER at startup of PMS171B
```
MCU_NAME: PMS171B
OTP_ID: 2D36

0x0000:   0x0000    NOP
0x0001:   0x0070    WDRESET
0x0002:   0x2f00    MOV A, 0x00
0x0003:   0x0182    MOV IO(0x02), A  ;SP
0x0004:   0x2ff9    MOV A, 0xF9
0x0005:   0x018d    MOV IO(0x0D), A  ;PADIER
0x0006:   0x2fff    MOV A, 0xFF
0x0007:   0x018e    MOV IO(0x0E), A  ;PBDIER
0x0008:   0x2f00    MOV A, 0x00
0x0009:   0x01ba    MOV IO(0x3A), A  ;?
0x000a:   0x3df6    CALL 0x5F6
0x000b:   0x019a    MOV IO(0x1A), A  ;BGTR
0x000c:   0x2f70    MOV A, 0x70
0x000d:   0x01b5    MOV IO(0x35), A  ;MISC_LVR
0x000e:   0x300e    GOTO 0x00E
```
Note that padauk says in datasheet that PADIER is F9 at startup because it's set by IDE with they expect you are using

**Comment by kaweksl** [comment]
I think factory BG calibration value is in function at 0x5F6

`#define EASY_PDK_USE_FACTORY_BGTR() { __asm__("call #0x5f6\n mov "_ASMV(BGTR)",a\n"); }
`

**Comment by serisman** [comment]
> FPPA IDE also sets PADIER at startup of PMS171B
> 
> ```
> MCU_NAME: PMS171B
> OTP_ID: 2D36
> 
> 0x0000:   0x0000    NOP
> 0x0001:   0x0070    WDRESET
> 0x0002:   0x2f00    MOV A, 0x00
> 0x0003:   0x0182    MOV IO(0x02), A  ;SP
> 0x0004:   0x2ff9    MOV A, 0xF9
> 0x0005:   0x018d    MOV IO(0x0D), A  ;PADIER
> 0x0006:   0x2fff    MOV A, 0xFF
> 0x0007:   0x018e    MOV IO(0x0E), A  ;PBDIER
> 0x0008:   0x2f00    MOV A, 0x00
> 0x0009:   0x01ba    MOV IO(0x3A), A  ;?
> 0x000a:   0x3df6    CALL 0x5F6
> 0x000b:   0x019a    MOV IO(0x1A), A  ;BGTR
> 0x000c:   0x2f70    MOV A, 0x70
> 0x000d:   0x01b5    MOV IO(0x35), A  ;MISC_LVR
> 0x000e:   0x300e    GOTO 0x00E
> ```

That looks useful.  Where did you find or how did you generate that startup code?

> Note that padauk says in datasheet that PADIER is F9 at startup because it's set by IDE with they expect you are using

That's evil.  The datasheet should be about the hardware itself, not some compiler implementation.  But yeah, I guess they didn't provide any other way to program these, so they thought they were covered.

> I think factory BG calibration value is in function at 0x5F6

Based on that startup code, and the fact that it matches the other OTP addresses, I agree.

**Comment by david-sawatzke** [comment]
Thanks for the help/tips. It seems to work!
```sh
$ sudo ./easypdkprog -n PMS171B write Examples/helloworld_pms171b.ihx
Writing IC (186 words)... done.
Calibrating IC
* IHRC SYSCLK=8000000Hz @ 4.00V ... calibration result: 7982674Hz (0x41)  done.
$ sudo ./easypdkprog start
Running IC (5.00V)... IC started, press [Esc] to stop.
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
```

**Comment by freepdk** [comment]
>     * I'm not sure how to select which `CALIBRATE` macros for ilrc & bg are the right ones. I just left the ones from the pfs154 there for now.

Hi, your pull request looks very good already.

ILRCR in .INC file from PADAUK is defined at position 0x39
BGTR in .INC file from PADAUK is defined at position 0x1A

which are indeed exact same as PFS154.

Have you tried the tuning example: 
Go to "Examples/src" and have a look at "calib-and-fuse-demo.c"

You can either use the complete code to perform all tunings as a test or just extract the ILRC / IHRC parts.
(You can have multiple tunings in one source, easypdkprog will perform all of them).

JS

**Comment by david-sawatzke** [comment]
I feared these might not work, since PADIER isn't enabled per default:
```sh
$ easypdkprog -n PMS171B write Examples/src/build/calib-and-fuse-dem_pms171b.ihx
Writing IC (1535 words)... done.
Calibrating IC
* ILRC SYSCLK=50000Hz @ 4.00V ... calibration result: 74522Hz out of range.
ERROR: Calibration failed
```

So this seems to be the same situation as the pms152

**Comment by freepdk** [comment]
Ok, if you already know that you need PADIER, then better wait for the rework I plan to do:

https://www.eevblog.com/forum/blog/eevblog-1144-padauk-programmer-reverse-engineering/msg3110746/#msg3110746

**Comment by freepdk** [comment]
I started the rework in feature branch newcalibration.

14 bit calibration is finished and tested on PFS154 + PFS172

Have a look in Examples/src/easypdk/pfs154.h to see how new more simplified calibration can be used:
```
#define EASY_PDK_CALIBRATE_IHRC(frequency,millivolt) EASY_PDK_CALIBRATE_RC_M( EASY_PDK_CALTYPE_IHRC, 0x0B, frequency, millivolt )
#define EASY_PDK_CALIBRATE_ILRC(frequency,millivolt) EASY_PDK_CALIBRATE_RC_M( EASY_PDK_CALTYPE_ILRC, 0x39, frequency, millivolt )
#define EASY_PDK_CALIBRATE_BG()                      EASY_PDK_CALIBRATE_BG_M( 0x1A, 0x18, 0x19 )
```
The macros "EASY_PDK_CALIBRATE_RC_M" and "EASY_PDK_CALIBRATE_BG_M" have parameters now to specify the registers required for calibration. 

Definition and explanation is in Examples/src/easypdk/pdkcommon.h

**Comment by serisman** [comment]
> I started the rework in feature branch newcalibration.

JS,

That is excellent!  What about PA, PAC, PADIER?  I assume those are always at the same address (for all known ICs) and we don't need to override them?

If you have a minute, can you take a look at my new feature/device-includes branch:
https://github.com/free-pdk/easy-pdk-programmer-software/compare/development...serisman:feature/device-includes?expand=1

This isn't done yet, but I started a refactor of the include files to accomplish better separation of generic PDK hardware abstraction (the pdk/* directory that hopefully could be included in SDCC at some point), from the more specific to easy-pdk programmer things (the easy-pdk/* directory).

The pdk/* directory is structured a bit like the avr-gcc avr/* directory with an pdk/io.h that is all that needs to be included from a user program.

The idea is anyone should be able to use the pdk/* directory even if they might use a different programmer (not that one exists yet).

I also pulled in your new calibration code (just the include file side for now), which really helped clean things up.

**Comment by kaweksl** [comment]
> 
> That looks useful. Where did you find or how did you generate that startup code?
> 
I used FPPA IDE to compile minimal code as possible without any calibration (.ADJUST_IC DISABLE)
then used modified 'dispdk' from https://github.com/free-pdk/fppa-pdk-tools.git . (added OTP_ID to emucpu.c )

**Comment by david-sawatzke** [comment]
@freepdk the new calibration routines look good! When they're in `development`, I'll update this PR and we can merge it

**Comment by serisman** [comment]
> > That looks useful. Where did you find or how did you generate that startup code?
> 
> I used FPPA IDE to compile minimal code as possible without any calibration (.ADJUST_IC DISABLE)
> then used modified 'dispdk' from https://github.com/free-pdk/fppa-pdk-tools.git . (added OTP_ID to emucpu.c )

Thanks!  For reference purposes, it would be nice (although not a huge priority I suppose) if someone took the time to run through that process for all known ICs and check in the results somewhere.

**Comment by david-sawatzke** [comment]
Calibration works now:
```sh
$ ./easypdkprog --icname=PMS171B write Examples/src/build/comptest_pms171b.ihx
Writing IC (422 words)... done.
Calibrating IC
* ILRC SYSCLK=50000Hz @ 4.00V ... calibration result: 49147Hz (0x00)  done.
* IHRC SYSCLK=1000000Hz @ 5.00V ... calibration result: 996142Hz (0x3A)  done.
* BandGap ... calibration result: (0x80)  done.
```
@freepdk  This is (probably) ready to merge

**Pull request merged**
